# terraform pipeline
variables:
  VAULT_AUTH_ROLE: 'myproject-staging'
  AWS_DEFAULT_REGION : 'us-east-1'
  VAULT_ADDR: 'http://3.226.190.247:8200'
  IMAGE: "hashicorp/terraform:latest"
  TERRAFORM_DIR_APP: "terraform/resources/1_application"
  ENV: "dev"

include:
  - project: 'aqt/vault-authentication'
    file:
      - 'templates/vault-aws-auth.yml'
  - project: 'aqt/vault-authentication'
    file:
      - 'templates/terraform.yml'

.rules-config:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: manual

stages:
    - authenticate
    - awscli
    #- terraform-init
    - terraform

vault-job:
    image: hashicorp/vault:latest
    tags:
      - gitlab-shared-runner
    stage: authenticate
    extends: 
      - .vault-aws-auth
      - .rules-config

aws-auth:
    tags:
      - gitlab-shared-runner
    stage: awscli
    image: amazon/aws-cli:latest
    extends:
        - .aws-cli
    dependencies: ["vault-job"]
    needs: ["vault-job"]

# init: 
#   image: ${IMAGE}
#   tags:
#       - gitlab-shared-runner
#   script:
#     - terraform -chdir=${TERRAFORM_DIR_APP} init -reconfigure -upgrade -backend-config="../../environments/${ENV}/terraform.backendconfig"


0-terraform-init:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .tf-config
    - .0-terraform-init
  dependencies: ["vault-job"]
  needs: ["vault-job"]

1-terraform-fmt:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .tf-config
    - .1-terraform-fmt
  dependencies: ["vault-job","0-terraform-init"]
  needs: ["vault-job", "0-terraform-init" ]

2-terraform-validate:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .tf-config
    - .2-terraform-validate
  dependencies: ["vault-job","0-terraform-init","1-terraform-fmt"]
  needs: ["vault-job","0-terraform-init","1-terraform-fmt" ]

3-terraform-plan:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .tf-config
    - .3-terraform-plan
  dependencies: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate"]
  needs: ["vault-job", "0-terraform-init", "1-terraform-fmt", "2-terraform-validate" ]

4-terraform-apply:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .tf-config
    - .4-terraform-apply
    - .rules-config
  dependencies: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate","3-terraform-plan" ]
  needs: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate","3-terraform-plan" ]

5-terraform-destroy:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .tf-config
    - .5-terraform-destroy
    - .rules-config
  dependencies: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate","3-terraform-plan" ]
  needs: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate","3-terraform-plan" ]


  