# terraform pipeline
variables:
  VAULT_AUTH_ROLE: 'myproject-staging'
  AWS_DEFAULT_REGION : 'us-east-1'
  VAULT_ADDR: 'http://3.226.190.247:8200'
  IMAGE: "hashicorp/terraform:1.6.3"
  TERRAFORM_DIR_APP: "terraform/resources/1_application"
  ENV: "dev"

include:
  - project: 'aqt/vault-authentication'
    file:
      - 'templates/vault-aws-auth.yml'
  - project: 'aqt/vault-authentication'
    file:
      - 'templates/terraform.yml'

.rules-config:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: manual

stages:
    - authenticate
    - awscli
    - terraform-init
    - terraform

vault-job:
    image: hashicorp/vault:latest
    tags:
      - gitlab-shared-runner
    stage: authenticate
    extends: 
      - .vault-aws-auth
      - .rules-config

aws-auth:
    tags:
      - gitlab-shared-runner
    stage: awscli
    image: amazon/aws-cli:latest
    extends:
        - .aws-cli
    dependencies: ["vault-job"]
    needs: ["vault-job"]

init: 
  image: 
    name: hashicorp/terraform:latest
    entrypoint: [""]
  stage: terraform-init
  tags:
      - gitlab-shared-runner
  #before_script:
  #  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tmmcops.com".insteadOf "https://gitlab.tmmcops.com"
  script:
    - echo "terraform init running on ${TERRAFORM_DIR_APP} directory and ${ENV} as environment"
    - pwd
    - cd /usr/local/bin/
    - ls
    - terraform --version
    - terraform -chdir=${TERRAFORM_DIR_APP} init -backend-config="../../environments/${ENV}/terraform.backendconfig"


0-terraform-init:
  tags:
      - gitlab-shared-runner
  stage: terraform
  image: ${IMAGE}
  extends:
    - .0-terraform-init
  dependencies: ["vault-job"]
  needs: ["vault-job"]

1-terraform-fmt:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .1-terraform-fmt
  dependencies: ["vault-job","0-terraform-init"]
  needs: ["vault-job", "0-terraform-init" ]

2-terraform-validate:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .2-terraform-validate
  dependencies: ["vault-job","0-terraform-init","1-terraform-fmt"]
  needs: ["vault-job","0-terraform-init","1-terraform-fmt" ]

3-terraform-plan:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .3-terraform-plan
  dependencies: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate"]
  needs: ["vault-job", "0-terraform-init", "1-terraform-fmt", "2-terraform-validate" ]

4-terraform-apply:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .4-terraform-apply
    - .rules-config
  dependencies: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate","3-terraform-plan" ]
  needs: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate","3-terraform-plan" ]

5-terraform-destroy:
  tags:
      - gitlab-shared-runner
  stage: terraform
  extends:
    - .5-terraform-destroy
    - .rules-config
  dependencies: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate","3-terraform-plan" ]
  needs: ["vault-job","0-terraform-init","1-terraform-fmt","2-terraform-validate","3-terraform-plan" ]


  